### ISSUE TITLE
[To Do] Thesauri are not loaded by default on deployment

### ISSUE THREAD

**Issue by howaskew** [AstunTechnology/os-custom-geonetwork#10] opened 2021-03-22 16:23 UTC
"By default the following thesauri should be loaded when as part of the deployment:
INSPIRE service taxonomy: http://geonetwork-opensource.org/inspire-service-taxonomy
GEMET - INSPIRE themes: http://inspire.ec.europa.eu/theme
GEMET concept thesaurus: http://geonetwork-opensource.org/gemet"

Of these 3, only the GEMET - INSPIRE themes URL works.

**Comment by archaeogeek** [comment] 2021-03-23 11:24
Should be fixed by c5b6e8fe474f82549361b636c2a160447c1b6b8d

**Comment by howaskew** [comment] 2021-04-13 14:14
@archaeogeek Hi, sorry- should this be working now? These 3 were lost from the live version.

**Comment by archaeogeek** [comment] 2021-04-13 14:16
hmm, yes it should be working, but clearly isn't- and manually loading the thesauri gives an error. I'll look at the log files...

**Comment by archaeogeek** [comment] 2021-04-13 14:19
it's working again now!

**Comment by howaskew** [comment] 2021-04-13 14:20
I added INSPIRE themes manually

**Comment by archaeogeek** [comment] 2021-04-13 14:26
Oh, that's a slightly different problem. I think it just needs reindexing, so I'm trying that

**Comment by archaeogeek** [comment] 2021-04-13 14:39
I might need to do a quick redeploy to pick up the changes. I've seen this before and it can be a bit sticky... I'm in the middle of something now so could I do that at around 5pm, or do you need it sooner?

**Comment by howaskew** [comment] 2021-04-13 14:43
No mad rush, we're still not broadcasting the UI massively. Just tried to demo internally and cosmetically it wasn't great. Whenever suits you.

**Comment by archaeogeek** [comment] 2021-04-13 14:48
Oh... I think I know what's going on... let me take a look again

**Comment by archaeogeek** [comment] 2021-04-13 15:26
I'm slightly mystified... I can replicate **and fix** the problem on my test version of your site but the live site is stubbornly refusing to behave. I'll do a docker-compose redeploy later and see if that sorts it out

**Comment by howaskew** [comment] 2021-04-13 15:29
Ok!

**Comment by archaeogeek** [comment] 2021-04-13 16:56
Well, I have tracked down the difference between the two systems, and can see what the problem is, but I can't (as of yet) get it to switch to what it should be. 

This was a new issue for me- basically if you delete all the language options in the admin console -> settings -> user interface then you lose the ability to define a language for the thesauri. Nothing shows in the interface, but when viewing a thesaurus if you try to "switch language" then you don't have any options. Then when the thesauri are indexed the label defaults to the URI rather than the language label, and you get the result we're seeing.

So I've defined just one language in the user interface, and can now "switch language" when viewing the thesaurus, but even re-indexing isn't fixing things. I assume I need to somehow force it to reindex the thesauri but I'm not sure how yet!

**Comment by archaeogeek** [comment] 2021-04-13 17:14
... and finally we're sorted! Phew!

**Comment by howaskew** [comment] 2021-04-14 09:08
Well done Jo. And I have to own up to causing that particular headache. I wanted to streamline the landing page and we didn't need the language selector. I was overzealous and deleted all the options on the UI settings page. Sorry!

**Comment by archaeogeek** [comment] 2021-04-14 09:10
ha, yes the trick is to delete all but one of the languages. However, I think I'm going to submit it as a bug so that it warns you of Bad Things Happening if you delete all the options.

**Closed** 2021-04-14 09:09 UTC
Labels: enhancement
